// Mocks generated by Mockito 5.4.6 from annotations
// in footverse/test/features/product/providers/product_detail_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:footverse/features/product/models/product_detail_response.dart'
    as _i3;
import 'package:footverse/features/product/models/product_summary_response.dart'
    as _i6;
import 'package:footverse/features/product/models/review_response.dart' as _i7;
import 'package:footverse/features/product/repositories/product_repository.dart'
    as _i4;
import 'package:footverse/shared/models/page_response.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePageResponse_0<T> extends _i1.SmartFake
    implements _i2.PageResponse<T> {
  _FakePageResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductDetailResponse_1 extends _i1.SmartFake
    implements _i3.ProductDetailResponse {
  _FakeProductDetailResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i4.ProductRepository {
  @override
  _i5.Future<_i2.PageResponse<_i6.ProductSummaryResponse>> searchProducts({
    String? name,
    int? brandId,
    int? categoryId,
    int? page = 0,
    int? size = 20,
    _i4.ProductSort? sort,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchProducts, [], {
              #name: name,
              #brandId: brandId,
              #categoryId: categoryId,
              #page: page,
              #size: size,
              #sort: sort,
            }),
            returnValue:
                _i5.Future<_i2.PageResponse<_i6.ProductSummaryResponse>>.value(
                  _FakePageResponse_0<_i6.ProductSummaryResponse>(
                    this,
                    Invocation.method(#searchProducts, [], {
                      #name: name,
                      #brandId: brandId,
                      #categoryId: categoryId,
                      #page: page,
                      #size: size,
                      #sort: sort,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<_i2.PageResponse<_i6.ProductSummaryResponse>>.value(
                  _FakePageResponse_0<_i6.ProductSummaryResponse>(
                    this,
                    Invocation.method(#searchProducts, [], {
                      #name: name,
                      #brandId: brandId,
                      #categoryId: categoryId,
                      #page: page,
                      #size: size,
                      #sort: sort,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.PageResponse<_i6.ProductSummaryResponse>>);

  @override
  _i5.Future<_i3.ProductDetailResponse> getProduct(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProduct, [id]),
            returnValue: _i5.Future<_i3.ProductDetailResponse>.value(
              _FakeProductDetailResponse_1(
                this,
                Invocation.method(#getProduct, [id]),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i3.ProductDetailResponse>.value(
                  _FakeProductDetailResponse_1(
                    this,
                    Invocation.method(#getProduct, [id]),
                  ),
                ),
          )
          as _i5.Future<_i3.ProductDetailResponse>);

  @override
  _i5.Future<_i2.PageResponse<_i7.ReviewResponse>> getProductReviews(
    int? id, {
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getProductReviews,
              [id],
              {#page: page, #size: size},
            ),
            returnValue: _i5.Future<_i2.PageResponse<_i7.ReviewResponse>>.value(
              _FakePageResponse_0<_i7.ReviewResponse>(
                this,
                Invocation.method(
                  #getProductReviews,
                  [id],
                  {#page: page, #size: size},
                ),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i2.PageResponse<_i7.ReviewResponse>>.value(
                  _FakePageResponse_0<_i7.ReviewResponse>(
                    this,
                    Invocation.method(
                      #getProductReviews,
                      [id],
                      {#page: page, #size: size},
                    ),
                  ),
                ),
          )
          as _i5.Future<_i2.PageResponse<_i7.ReviewResponse>>);
}
