// Mocks generated by Mockito 5.4.6 from annotations
// in footverse/test/features/address/providers/address_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:footverse/features/address/models/address_request.dart' as _i5;
import 'package:footverse/features/address/models/address_response.dart' as _i2;
import 'package:footverse/features/address/repositories/address_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAddressResponse_0 extends _i1.SmartFake
    implements _i2.AddressResponse {
  _FakeAddressResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AddressRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddressRepository extends _i1.Mock implements _i3.AddressRepository {
  @override
  _i4.Future<List<_i2.AddressResponse>> getAddresses() =>
      (super.noSuchMethod(
            Invocation.method(#getAddresses, []),
            returnValue: _i4.Future<List<_i2.AddressResponse>>.value(
              <_i2.AddressResponse>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<_i2.AddressResponse>>.value(
                  <_i2.AddressResponse>[],
                ),
          )
          as _i4.Future<List<_i2.AddressResponse>>);

  @override
  _i4.Future<_i2.AddressResponse> createAddress(_i5.AddressRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#createAddress, [request]),
            returnValue: _i4.Future<_i2.AddressResponse>.value(
              _FakeAddressResponse_0(
                this,
                Invocation.method(#createAddress, [request]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.AddressResponse>.value(
              _FakeAddressResponse_0(
                this,
                Invocation.method(#createAddress, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.AddressResponse>);

  @override
  _i4.Future<_i2.AddressResponse> updateAddress(
    int? id,
    _i5.AddressRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAddress, [id, request]),
            returnValue: _i4.Future<_i2.AddressResponse>.value(
              _FakeAddressResponse_0(
                this,
                Invocation.method(#updateAddress, [id, request]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.AddressResponse>.value(
              _FakeAddressResponse_0(
                this,
                Invocation.method(#updateAddress, [id, request]),
              ),
            ),
          )
          as _i4.Future<_i2.AddressResponse>);

  @override
  _i4.Future<void> deleteAddress(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAddress, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
