// Mocks generated by Mockito 5.4.6 from annotations
// in footverse/test/features/product/screens/product_detail_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:footverse/features/product/models/product_detail_response.dart'
    as _i3;
import 'package:footverse/features/product/models/product_summary_response.dart'
    as _i7;
import 'package:footverse/features/product/models/review_response.dart' as _i8;
import 'package:footverse/features/product/repositories/product_repository.dart'
    as _i5;
import 'package:footverse/features/wishlist/models/add_wishlist_item_request.dart'
    as _i10;
import 'package:footverse/features/wishlist/models/wishlist_item_response.dart'
    as _i4;
import 'package:footverse/features/wishlist/repositories/wishlist_repository.dart'
    as _i9;
import 'package:footverse/shared/models/page_response.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePageResponse_0<T> extends _i1.SmartFake
    implements _i2.PageResponse<T> {
  _FakePageResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductDetailResponse_1 extends _i1.SmartFake
    implements _i3.ProductDetailResponse {
  _FakeProductDetailResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWishlistItemResponse_2 extends _i1.SmartFake
    implements _i4.WishlistItemResponse {
  _FakeWishlistItemResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i5.ProductRepository {
  @override
  _i6.Future<_i2.PageResponse<_i7.ProductSummaryResponse>> searchProducts({
    String? name,
    int? brandId,
    int? categoryId,
    int? page = 0,
    int? size = 20,
    _i5.ProductSort? sort,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchProducts, [], {
              #name: name,
              #brandId: brandId,
              #categoryId: categoryId,
              #page: page,
              #size: size,
              #sort: sort,
            }),
            returnValue:
                _i6.Future<_i2.PageResponse<_i7.ProductSummaryResponse>>.value(
                  _FakePageResponse_0<_i7.ProductSummaryResponse>(
                    this,
                    Invocation.method(#searchProducts, [], {
                      #name: name,
                      #brandId: brandId,
                      #categoryId: categoryId,
                      #page: page,
                      #size: size,
                      #sort: sort,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i6.Future<_i2.PageResponse<_i7.ProductSummaryResponse>>.value(
                  _FakePageResponse_0<_i7.ProductSummaryResponse>(
                    this,
                    Invocation.method(#searchProducts, [], {
                      #name: name,
                      #brandId: brandId,
                      #categoryId: categoryId,
                      #page: page,
                      #size: size,
                      #sort: sort,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i2.PageResponse<_i7.ProductSummaryResponse>>);

  @override
  _i6.Future<_i3.ProductDetailResponse> getProduct(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProduct, [id]),
            returnValue: _i6.Future<_i3.ProductDetailResponse>.value(
              _FakeProductDetailResponse_1(
                this,
                Invocation.method(#getProduct, [id]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i3.ProductDetailResponse>.value(
                  _FakeProductDetailResponse_1(
                    this,
                    Invocation.method(#getProduct, [id]),
                  ),
                ),
          )
          as _i6.Future<_i3.ProductDetailResponse>);

  @override
  _i6.Future<_i2.PageResponse<_i8.ReviewResponse>> getProductReviews(
    int? id, {
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getProductReviews,
              [id],
              {#page: page, #size: size},
            ),
            returnValue: _i6.Future<_i2.PageResponse<_i8.ReviewResponse>>.value(
              _FakePageResponse_0<_i8.ReviewResponse>(
                this,
                Invocation.method(
                  #getProductReviews,
                  [id],
                  {#page: page, #size: size},
                ),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i2.PageResponse<_i8.ReviewResponse>>.value(
                  _FakePageResponse_0<_i8.ReviewResponse>(
                    this,
                    Invocation.method(
                      #getProductReviews,
                      [id],
                      {#page: page, #size: size},
                    ),
                  ),
                ),
          )
          as _i6.Future<_i2.PageResponse<_i8.ReviewResponse>>);
}

/// A class which mocks [WishlistRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWishlistRepository extends _i1.Mock
    implements _i9.WishlistRepository {
  @override
  _i6.Future<List<_i4.WishlistItemResponse>> getWishlist() =>
      (super.noSuchMethod(
            Invocation.method(#getWishlist, []),
            returnValue: _i6.Future<List<_i4.WishlistItemResponse>>.value(
              <_i4.WishlistItemResponse>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i4.WishlistItemResponse>>.value(
                  <_i4.WishlistItemResponse>[],
                ),
          )
          as _i6.Future<List<_i4.WishlistItemResponse>>);

  @override
  _i6.Future<_i4.WishlistItemResponse> addProduct(
    _i10.AddWishlistItemRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addProduct, [request]),
            returnValue: _i6.Future<_i4.WishlistItemResponse>.value(
              _FakeWishlistItemResponse_2(
                this,
                Invocation.method(#addProduct, [request]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i4.WishlistItemResponse>.value(
                  _FakeWishlistItemResponse_2(
                    this,
                    Invocation.method(#addProduct, [request]),
                  ),
                ),
          )
          as _i6.Future<_i4.WishlistItemResponse>);

  @override
  _i6.Future<void> removeProduct(int? productId) =>
      (super.noSuchMethod(
            Invocation.method(#removeProduct, [productId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
